### ISSUE TITLE
Forbidden Access

### ISSUE THREAD

**Issue by mazzespazze** [juneidysoo/travian-compose#1]
After running the `docker-compose up` command, I get the app to run on my local. 

Though after writing all the different settings for the server, after selecting Create I get prompted the following:

```

Warning: mysqli_connect(): (HY000/2002): No such file or directory in /var/www/html/GameEngine/Database.php on line 439

Warning: mysqli_error() expects parameter 1 to be mysqli, bool given in /var/www/html/GameEngine/Database.php on line 453

Warning: mysqli_query() expects parameter 1 to be mysqli, bool given in /var/www/html/GameEngine/Database.php on line 429

Warning: mysqli_connect(): (HY000/2002): No such file or directory in /var/www/html/GameEngine/Database.php on line 439

Warning: mysqli_error() expects parameter 1 to be mysqli, bool given in /var/www/html/GameEngine/Database.php on line 453

Warning: mysqli_query() expects parameter 1 to be mysqli, bool given in /var/www/html/GameEngine/Database.php on line 429

Warning: mysqli_query() expects parameter 1 to be mysqli, bool given in /var/www/html/GameEngine/Database.php on line 633

Fatal error: Uncaught Error: Call to a member function multi_query() on bool in /var/www/html/GameEngine/Database.php:7067 Stack trace: #0 /var/www/html/install/process.php(184): MYSQLi_DB->createDbStructure() #1 /var/www/html/install/process.php(22): Process->createStruc() #2 /var/www/html/install/process.php(224): Process->__construct() #3 {main} thrown in /var/www/html/GameEngine/Database.php on line 7067
```

**Comment by juneidy** [comment]
You probably did not set the correct parameter in the SQL section of the configuration.

**Comment by mazzespazze** [comment]
@juneidy would you be able to elaborate on that? In my understanding I just had to set "travian" as admin, password and database.

**Comment by andreapavoni** [comment]
@mazzespazze I got the same problem, the solution was to set `mysql` (instead of `localhost`) for the MySQL hostname in the database section. This is because inside docker you access the db by the image name:

```yaml
services:
   travian:
    ...

   mysql: # <- this is the name to refer to mysql in your docker networking
      image: "mysql:8.0.29-debian"
      ...
``` 

After fixing this, the installation went smooth ;-)

**Comment by mazzespazze** [comment]
That worked! @andreapavoni 
This specific issue can be closed. @juneidy 
There are a couple of bugs in-game, but it's not a docker issue.

**Comment by andreapavoni** [comment]
@mazzespazze yes, there are many bugs and I don't remember some details (like if server speed influences building times too) because I don't play it since years.

btw, if you're planning to run a public instance, please ping me ;-) I'm continuing the development of my Go clone.

**Comment by mazzespazze** [comment]
@andreapavoni I'll try to run it for a few weeks on my local first to check all the potential issue. ;) 
On a side note, any clue on how to re-start the server? Even by removing all the docker data it seems to remember everything. I would like to re-start from the same installation menu.

Except deleting the folder TravianZ of course.

**Comment by andreapavoni** [comment]
@mazzespazze well, trying it locally right now at 5x, the map is bugged as hell (most notably, it doesn't recognize negative values for coordinates) and it's particularly slow (I've read somewhere that each page load in TravianZ makes around 400 db queries, but I didn't check the code).

I'm going to try this fork: https://github.com/martinambrus/TravianZ

the author did run an instance (now gone) for some weeks, and it worked decently (except that the admins were clearly playing with some boosting trough the admin panel), it stopped working with the arrive of Natars, so I don't know if it's possible to complete an entire round of server.

regarding the reset: stop the containers (you don't need to remove docker images at all, they're read-only, nothing can be written there) then check `./appdata/mysql/data`, it should suffice to remove the `data` directory.

**Comment by mazzespazze** [comment]
Yeah the map is bugged. You need to substitute "-" with "+" on the left part for most of the entries. I wasn't aware that making a game from 2006 would require so much effort. 
And as you say, Natars have always something. Mostly I'm not sure the artifacts will ever work. I'll keep using this instance, as for the moment I have only noticed the map as the main issue. 

But I'm so looking forward for your Go implementation! @andreapavoni

**Comment by andreapavoni** [comment]
@mazzespazze 

>  I wasn't aware that making a game from 2006 would require so much effort.

IIRC the first version of TravianZ (the clone) has been started around 2008-2010 and improved during the years by many people (mostly from Ukraine, Russia and East-Europe). It's clear that, beside the state of PHP development in those years, the authors were very skilled with math (like Kirilloid), but the overall architecture design compared to today's standard is a bit... poor.

The most challenging parts which I'm aware of (by checking the code) are:

- map creation with valleys of random topology, oases, etc... (they did it all through a huge SQL query)
- handling times and processing of tasks/events/attacks/etc... (basically, on each page load, it checks if the ones regarding the player are completed and process them on the fly in the right order)
- handling troops/buildings requirements/contraints, tribe specific features and everything non-standard behaviour (ex: double building queue only for Romans, Brewery only for Teutons, having infrastructure at level X before building Y, etc...)

luckily, I already have the right math formulas for the combat system, which is another very complex part to build if you decide to go for reverse engineering of the official Travian.

**Comment by juneidy** [comment]
> Yeah the map is bugged. You need to substitute "-" with "+" on the left part for most of the entries.

See https://github.com/Shadowss/TravianZ/issues/27#issuecomment-979739112

Changing that will fix the map "-" and "+"
