### ISSUE TITLE
Map with coordinate problem

### ISSUE THREAD

**Issue by GustoVasconcelos** [juneidysoo/travian-compose#3]
The map has a problem with the coordinates. Once installed, it already has this bug. Could anyone test to see if it's just me that's like this?

https://github.com/user-attachments/assets/4e521e36-26a4-456c-a43f-2525246243f4

**Comment by juneidy** [comment]
It's been discussed in the past issue and the TravianZ repo multiple times. Please use the search.

https://github.com/Shadowss/TravianZ/issues/27#issuecomment-979739112

**Comment by GustoVasconcelos** [comment]
> It's been discussed in the past issue and the TravianZ repo multiple times. Please use the search.
> 
> [Shadowss/TravianZ#27 (comment)](https://github.com/Shadowss/TravianZ/issues/27#issuecomment-979739112)

Forgive me, I hadn't seen this problem, as it was an old problem, I didn't think it was related.
Thank you!
